### ISSUE TITLE
Valor do iterator em posição inexistente e condição invalidando o laço de repetição

### ISSUE THREAD

**Issue by pedro-hbraga** [pedro-hbraga/lab05ticketmachine#10]
Na classe Troco, bloco de código da linha 72 - 77 o valor do iterator ("i") está iniciando em uma posição da fila inexistente e incremento está incorreto (++).
Também existe um operador lógico "AND" que está invalidando a condição necessária para realizar o loop ao comparar o valor de uma variável que está sempre nula.

**Comment by GustavoVersolato** [comment]
Corrigido
![image](https://github.com/pedro-hbraga/lab05ticketmachine/assets/71678490/811b6f0f-1faa-471b-9795-a1aebea0f476)
