### ISSUE TITLE
Condição obtendo sempre o mesmo valor da lista

### ISSUE THREAD

**Issue by pedro-hbraga** [pedro-hbraga/lab05ticketmachine#11]
Na classe TicketMachine, o método inserir possui um bloco de código condicional (if) entre as linhas 25 - 27 que possui o mesmo valor sendo comparado sempre, pois é valor da lista obtido é sempre o valor 1 ao invés de obter o iterator ("i").

**Comment by GustavoVersolato** [comment]
Corrigido
![image](https://github.com/pedro-hbraga/lab05ticketmachine/assets/71678490/2a3081d8-98fa-4183-8e04-6862c348984b)
