### ISSUE TITLE
Método retornando tipagem incorreta

### ISSUE THREAD

**Issue by pedro-hbraga** [pedro-hbraga/lab05ticketmachine#13]
O método getTroco(), da classe TicketMachine, está retornando Integer quando deveria retornar PapelMoeda.

**Comment by GustavoVersolato** [comment]
Corrigido
![image](https://github.com/pedro-hbraga/lab05ticketmachine/assets/71678490/b7165db2-99a9-4bea-bc45-0c1e32c0f0f4)
