### ISSUE TITLE
Loop while infinito - linha 16-18

### ISSUE THREAD

**Issue by GustavoVersolato** [pedro-hbraga/lab05ticketmachine#2]
Caso entre na condição que foi feita no While da linha 16- 18 da classe Troco está sendo impossível de sair

**Comment by pedro-hbraga** [comment]
Loop corrigido e valor sendo abatido a cada passagem do loop.

![image](https://github.com/pedro-hbraga/lab05ticketmachine/assets/73506802/829b3699-35e5-48b6-bc13-d8dd6293a4ad)
