### ISSUE TITLE
Loop while infinito - linha 21-23

### ISSUE THREAD

**Issue by GustavoVersolato** [pedro-hbraga/lab05ticketmachine#3]
Caso entre na condição que foi feita no While da linha 21- 23 da classe Troco está sendo impossível de sair

**Comment by pedro-hbraga** [comment]
Loop corrigido e valor sendo abatido a cada passagem do loop.

![image](https://github.com/pedro-hbraga/lab05ticketmachine/assets/73506802/9d2a66f1-aed6-48df-aba9-f0431455006a)
