### ISSUE TITLE
Loop while infinito - linha 41 - 43

### ISSUE THREAD

**Issue by pedro-hbraga** [pedro-hbraga/lab05ticketmachine#7]
Caso entre na condição que foi feita no While da linha 41- 43 da classe Troco está sendo impossível de sair

**Comment by GustavoVersolato** [comment]
Corrigido
![image](https://github.com/pedro-hbraga/lab05ticketmachine/assets/71678490/820886b0-e26d-46fa-a829-6a9a988899e0)
