### ISSUE TITLE
Nota sendo sobrescrita 

### ISSUE THREAD

**Issue by GustavoVersolato** [pedro-hbraga/lab05ticketmachine#8]
Na classe Troco, linha 44 o valor da nota 5 está sendo sobrescrita pelo valor 2.

**Comment by pedro-hbraga** [comment]
Correções efetuadas.

![image](https://github.com/pedro-hbraga/lab05ticketmachine/assets/73506802/6471c158-b58c-4a11-a235-5919c48be983)
