### ISSUE TITLE
Valor do iterator em posição inexistente

### ISSUE THREAD

**Issue by pedro-hbraga** [pedro-hbraga/lab05ticketmachine#9]
Na classe Troco, bloco de código da linha 61 - 65 o valor do iterator ("i") está iniciando em uma posição da fila inexistente e incremento está incorreto (++)

**Comment by GustavoVersolato** [comment]
Corrigido
![image](https://github.com/pedro-hbraga/lab05ticketmachine/assets/71678490/8e350fb8-071d-4933-9141-c6c9340e3041)
